print([x*x for x in range(1,11)])
print([x for x in range(1,21) if x%2==0])
print([x for x in range(1,21) if x%2==1])
print([x for x in range(1,31) if x%3==0])
print([x  for x in "hello"])
print([x for x in range(-1,-11,-1)])
print([x*x for x in range(1,16) if x%2==0])
print([li[0] for li in ['apple','banana','cherry','date']])
print([len(li) for li in ['apple','banana','cherry','date']])
